"""
Paper Writer Agent -  it uses all agent outputs to generate comprehensive paper
"""

import logging
import os
from dotenv import load_dotenv
from datetime import datetime
from typing import Dict, Any

load_dotenv()

try:
    import google.generativeai as genai
    GEMINI_AVAILABLE = True
except ImportError:
    GEMINI_AVAILABLE = False


class PaperWriterAgent:
    """Generates 2500-3000 word papers using Gemini API + agent context"""
    
    def __init__(self, memory_store):
        self.memory = memory_store
        self.logger = logging.getLogger("PaperWriterAgent")
        self.ai_model = None
        
        if GEMINI_AVAILABLE:
            api_key = os.getenv('GEMINI_API_KEY')
            if api_key:
                try:
                    genai.configure(api_key=api_key)
                    self.ai_model = genai.GenerativeModel('gemini-2.5-flash')
                    self.logger.info("✓ Gemini AI enabled")
                except Exception as e:
                    self.logger.error(f"Gemini setup failed: {e}")
    
    async def write_paper(self, all_outputs: Dict) -> dict:
        """
        Generate 3000-word paper using all agent outputs
        
        Args:
            all_outputs: Outputs from all agents
            
        Returns:
            Complete research paper
        """
        self.logger.info("Generating research paper with Gemini...")
        
        if not self.ai_model:
            return self._generate_error_paper()
        
        # Extract agent outputs
        problem = all_outputs.get('research_problem', {})
        hypothesis = all_outputs.get('hypothesis', {})
        experiment = all_outputs.get('experiment_design', {})
        analysis = all_outputs.get('analysis', {})
        
        # Generate with Gemini
        try:
            paper_content = await self._generate_with_gemini(
                problem, hypothesis, experiment, analysis
            )
            
            title = self._extract_title(paper_content, problem.get('domain', 'Research'))
            word_count = len(paper_content.split())
            
            result = {
                "title": title,
                "content": paper_content,
                "word_count": word_count,
                "ai_model": "gemini-1.5-flash",
                "generated_at": datetime.now().isoformat()
            }
            
            self.logger.info(f"✓ Paper generated: {word_count} words")
            return result
            
        except Exception as e:
            self.logger.error(f"Generation failed: {e}")
            return self._generate_error_paper()
    
    async def _generate_with_gemini(self, problem: Dict, hypothesis: Dict,
                                   experiment: Dict, analysis: Dict) -> str:
        """Generate full paper with all agent context"""
        
        # Build context from agents
        context = f"""
RESEARCH CONTEXT FROM AGENTS:

1. PROBLEM (from Problem Finder Agent):
   - Domain: {problem.get('domain')}
   - Problem: {problem.get('problem_statement')}
   - Gap: {problem.get('research_gap')}
   - Keywords: {', '.join(problem.get('keywords', []))}
   - Papers Analyzed: {problem.get('papers_found', 0)}

2. HYPOTHESIS (from Hypothesis Agent):
   - Main: {hypothesis.get('hypothesis')}
   - Type: {hypothesis.get('hypothesis_type')}
   - Variables: IV={hypothesis.get('independent_variables', [])}, DV={hypothesis.get('dependent_variables', [])}

3. METHODOLOGY (from Experiment Designer):
   - Design: {experiment.get('experiment_type')}
   - Sample Size: {experiment.get('sample_size', 'N/A')}
   - Approach: {experiment.get('methodology', {}).get('approach', 'Experimental')}

4. ANALYSIS (from Data Analyst):
   - Key Finding: {analysis.get('key_finding', 'Statistical significance observed')}
   - Interpretation: {analysis.get('interpretation', 'Results support hypothesis')}
"""

        prompt = f"""You are an expert academic research writer. Write a COMPLETE, PROFESSIONAL research paper using the context provided by multiple AI agents.

{context}

REQUIREMENTS:
- Length: 2500-3000 words
- Format: Academic research paper with proper structure
- Citations: Include 12-15 realistic citations [Author et al., Year]
- Style: Formal academic writing
- Depth: Comprehensive analysis with technical details
- Integration: Use ALL agent outputs in relevant sections

STRUCTURE (MUST INCLUDE ALL SECTIONS):

# [Compelling Title about {problem.get('domain', 'Research')}]

**Generated by AutoResearch Lab Multi-Agent System**
**Date: {datetime.now().strftime('%B %d, %Y')}**

---

## Abstract
(300-350 words summary covering background, objectives, methods, results, conclusion)

## 1. Introduction

### 1.1 Background and Context
(400-500 words explaining the field, importance, and recent developments)

### 1.2 Problem Statement
(Use Problem Finder output: {problem.get('problem_statement')})
(300 words elaborating on the specific problem)

### 1.3 Research Gap
(Use: {problem.get('research_gap')})
(200 words explaining what's missing in literature)

### 1.4 Research Objectives
(150 words stating clear research goals)

## 2. Literature Review

### 2.1 Theoretical Foundations
(400 words discussing key theories and frameworks)

### 2.2 Previous Research
(500 words reviewing 6-8 relevant studies with citations [Author, Year])

### 2.3 Current State
(300 words synthesizing current knowledge)

### 2.4 Identified Gaps
(200 words highlighting specific gaps based on {problem.get('papers_found', 0)} papers analyzed)

## 3. Methodology

### 3.1 Research Design
(Use Experiment Designer output: {experiment.get('experiment_type')})
(300 words detailing the {experiment.get('experiment_type')} approach)

### 3.2 Hypothesis Formulation
(Use Hypothesis Agent output: {hypothesis.get('hypothesis')})
**H1:** {hypothesis.get('hypothesis')}
**H0:** {hypothesis.get('null_hypothesis', 'No significant effect')}
(200 words explaining hypothesis rationale)

### 3.3 Variables
(200 words operationalizing IV, DV, CV from agent outputs)

### 3.4 Sample and Procedure
(300 words describing {experiment.get('sample_size', 'sample size')} and procedures)

### 3.5 Data Collection and Analysis
(250 words explaining measurement and statistical methods)

## 4. Results

### 4.1 Descriptive Statistics
(200 words presenting sample characteristics)

### 4.2 Hypothesis Testing
(Use Analysis Agent output: {analysis.get('key_finding', 'findings')})
(300 words reporting statistical tests with t-values, p-values, effect sizes)

### 4.3 Key Findings
(250 words highlighting main results)

### 4.4 Additional Observations
(200 words reporting secondary findings)

## 5. Discussion

### 5.1 Interpretation of Results
(400 words explaining what results mean)

### 5.2 Theoretical Implications
(300 words discussing contributions to theory)

### 5.3 Practical Implications
(250 words describing real-world applications)

### 5.4 Comparison with Literature
(300 words relating findings to previous research)

### 5.5 Limitations
(200 words acknowledging study constraints)

### 5.6 Future Research Directions
(200 words suggesting next steps)

## 6. Conclusion
(400 words summarizing contributions, implications, and final thoughts)

## References
(12-15 references in format: Author, A., & Author, B. (Year). Title. Journal, volume(issue), pages. DOI)

CRITICAL INSTRUCTIONS:
- Reach 2500-3000 words total
- Use formal academic tone throughout
- Integrate ALL agent outputs naturally
- Include specific technical details
- Cite 12-15 realistic sources
- Make it publication-ready
- Be comprehensive and thorough

Write the COMPLETE paper now:"""

        response = self.ai_model.generate_content(
            prompt,
            generation_config=genai.types.GenerationConfig(
                max_output_tokens=8000,
                temperature=0.7,
            )
        )
        
        return response.text
    
    def _extract_title(self, content: str, domain: str) -> str:
        """Extract title from content"""
        lines = content.split('\n')
        for line in lines[:10]:
            line = line.strip()
            if line.startswith('# ') and 'Abstract' not in line:
                return line[2:].strip()
        
        return f"Advanced Research in {domain.title()}: A Comprehensive Study"
    
    def _generate_error_paper(self) -> dict:
        """Error fallback"""
        return {
            "title": "Error: Paper Generation Failed",
            "content": "# Error\n\nCould not generate paper. Check GEMINI_API_KEY in .env file.",
            "word_count": 10,
            "ai_model": "error",
            "generated_at": datetime.now().isoformat()
        }